### ISSUE TITLE
Exception java.lang.NoSuchFieldError: No field savedCardButton of type I

### ISSUE THREAD

**Issue by bktowett** [Flutterwave/rave-android#1]
Hello, I am getting the following error when I run the following code block:
`new RavePayManager(FlutterTest.this).setAmount(1000)
                        .setCountry("NG")
                        .setCurrency("NGN")
                        .setEmail("brian@kiptoo.com")
                        .setfName("Brian")
                        .setlName("Kiptoo")
                        .setNarration("test")
                        .setPublicKey("publicKey)
                        .setSecretKey(secretkey)
                        .setTxRef("rtru")
                        .acceptAccountPayments(true)
                        .acceptCardPayments(true)
                        .onStagingEnv(true)
                        .initialize();`

Here is the full log

Exception java.lang.NoSuchFieldError: No field savedCardButton of type I in class Lcom/flutterwave/raveandroid/R$id; or its superclasses (declaration of 'com.flutterwave.raveandroid.R$id' appears in /data/app/com.mypackagenamehere-2/base.apk:classes56.dex)
com.flutterwave.raveandroid.card.CardFragment.onCreateView (CardFragment.java:110)
android.support.v4.app.Fragment.performCreateView (Fragment.java:2192)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1299)
android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManager.java:1528)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1595)
android.support.v4.app.BackStackRecord.executeOps (BackStackRecord.java:758)
android.support.v4.app.FragmentManagerImpl.executeOps (FragmentManager.java:2363)
android.support.v4.app.FragmentManagerImpl.executeOpsTogether (FragmentManager.java:2149)
android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps (FragmentManager.java:2103)
android.support.v4.app.FragmentManagerImpl.execSingleAction (FragmentManager.java:1984)
android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss (BackStackRecord.java:626)
android.support.v4.app.FragmentPagerAdapter.finishUpdate (FragmentPagerAdapter.java:143)
android.support.v4.view.ViewPager.populate (ViewPager.java:1268)
android.support.v4.view.ViewPager.populate (ViewPager.java:1116)
android.support.v4.view.ViewPager.onMeasure (ViewPager.java:1642)
android.view.View.measure (View.java:19963)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6097)
android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1464)
android.widget.LinearLayout.measureVertical (LinearLayout.java:758)
android.widget.LinearLayout.onMeasure (LinearLayout.java:640)
android.view.View.measure (View.java:19963)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6097)
android.support.design.widget.CoordinatorLayout.onMeasureChild (CoordinatorLayout.java:714)
android.support.design.widget.CoordinatorLayout.onMeasure (CoordinatorLayout.java:786)
android.view.View.measure (View.java:19963)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6097)
android.widget.FrameLayout.onMeasure (FrameLayout.java:185)
android.support.v7.widget.ContentFrameLayout.onMeasure (ContentFrameLayout.java:139)
android.view.View.measure (View.java:19963)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6097)
android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1464)
android.widget.LinearLayout.measureVertical (LinearLayout.java:758)
android.widget.LinearLayout.onMeasure (LinearLayout.java:640)
android.view.View.measure (View.java:19963)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6097)
android.widget.FrameLayout.onMeasure (FrameLayout.java:185)
android.view.View.measure (View.java:19963)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6097)
android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1464)
android.widget.LinearLayout.measureVertical (LinearLayout.java:758)
android.widget.LinearLayout.onMeasure (LinearLayout.java:640)
android.view.View.measure (View.java:19963)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6097)
android.widget.FrameLayout.onMeasure (FrameLayout.java:185)
com.android.internal.policy.DecorView.onMeasure (DecorView.java:689)
android.view.View.measure (View.java:19963)
android.view.ViewRootImpl.performMeasure (ViewRootImpl.java:2308)
android.view.ViewRootImpl.measureHierarchy (ViewRootImpl.java:1392)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:1645)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1280)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6451)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:943)
android.view.Choreographer.doCallbacks (Choreographer.java:755)
android.view.Choreographer.doFrame (Choreographer.java:690)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:929)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6334)
java.lang.reflect.Method.invoke (Method.java)

**Comment by biodunalfet** [comment]
If you have any layouts named fragment_card.xml, rename it :)

**Comment by saintjab** [comment]
I am having similar issue though I don't have any layout with such name. Exception in mine is

> No static field rave_progressContainer of type I in class Lcom/flutterwave/raveandroid/R$id; or its superclasses (declaration of 'com.flutterwave.raveandroid.R$id'
