### ISSUE TITLE
Invalid network selected for Ghana Mobile Money

### ISSUE THREAD

**Issue by megamendhie** [Flutterwave/rave-android#124]
Payment with Ghana Mobile Money returns Invalid network selected even when the correct network is selected. It happens especially if the phone number was typed before the number selected.

**Comment by sammie-gh** [comment]
same it works sometimes but goes back to this issue u guys are affecting business. please fix this

**Comment by biodunalfet** [comment]
Hi @sammie-gh,

This issue has been resolved in the latest version. What version are you using at the moment?

**Comment by sammie-gh** [comment]
1.0.39

**Comment by sammie-gh** [comment]
Will try updating and let you know
