### ISSUE TITLE
Payment verification on Android plugin

### ISSUE THREAD

**Issue by nzeakokosi7** [Flutterwave/rave-android#14]
I've been testing rave with live cards on the android plugin. After every successful payment. The OnActivityResult still returns an error message, meanwhile I've been debited and rave has already sent me an email confirming a successful payment. Please help

**Comment by biodunalfet** [comment]
What version of the sdk are you using?

**Comment by nzeakokosi7** [comment]
Uhm 1.0.6 the version on your documentation then I also tried 1.0.8 same
issue. Please I'm looking for a way to parse the intent data and read the
status and chargeResponse and other meta data too from the
onActivityResult. Thanks

**Comment by biodunalfet** [comment]
Use the current version. 1.0.10.
You can get the raw json response from the intent's extra like this
```
if (requestCode == RaveConstants.RAVE_REQUEST_CODE && data != null) {
        String message = data.getStringExtra("response");
        Log.d("response", message);
}
```
You can then get the response from the logs and parse it as you wish.

**Comment by nzeakokosi7** [comment]
First of all thank you so much for the version upgrade, secondly I'm using
firebase so parsing it into a string makes it almost useless for the client
side configurations I need. Is there another way of picking the exact meta
data I need instead of getting everything as a string?
Thanks once again

**Comment by biodunalfet** [comment]
@nzeakokosi7 You can parse it using `JSONObject` and `JSONString`. E.g if you want to extract the `rave_ref` you can do this
```
    val response = JSONObject(message) . //pass in the json string from onActivityResult as message
    val dataObj = response.getJSONObject("data")
    val raveRef = dataObj.getString("rave_ref")
```

**Comment by nzeakokosi7** [comment]
Thank you so much, I'd try it out and revert back to you.

**Comment by ma-za-kpe** [comment]
This issue still persists even now:
rave =     implementation 'com.github.flutterwave.rave-android:rave_android:2.1.39'
android 10.
