### ISSUE TITLE
I don't receive a "transaction successful" update

### ISSUE THREAD

**Issue by maykhid** [Flutterwave/rave-android#145]
So i'm new to rave and i'm having a hard time using it. I'm using the rave sandbox to test it out, but after i input the test card details, and the OTP i usually don't get a "transaction successful" notification i just get a white screen displaying "not found" for just a few seconds then closes. But the funny thing is that it records that the transaction was successful when i go through my transactions. Am i doing something wrong? Help anyone.

**Comment by jeremiahVaris** [comment]
Hi @maykhid please ensure to override `onActivityResult` in the activity from which you call the RavePayManager, to handle the transaction result in your app. An example is shown below:
```java

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        /*
         *  We advise you to do a further verification of transaction's details on your server to be
         *  sure everything checks out before providing service or goods.
        */
        if (requestCode == RaveConstants.RAVE_REQUEST_CODE && data != null) {
            String message = data.getStringExtra("response");
            if (resultCode == RavePayActivity.RESULT_SUCCESS) {
                // Transaction is successful, do something. 
                Toast.makeText(this, "SUCCESS " + message, Toast.LENGTH_SHORT).show();
            }
            else if (resultCode == RavePayActivity.RESULT_ERROR) {
                Toast.makeText(this, "ERROR " + message, Toast.LENGTH_SHORT).show();
            }
            else if (resultCode == RavePayActivity.RESULT_CANCELLED) {
                Toast.makeText(this, "CANCELLED " + message, Toast.LENGTH_SHORT).show();
            }
        }
        else {
            super.onActivityResult(requestCode, resultCode, data);
        }
    }
```

**Comment by maykhid** [comment]
Hmm..I overrode the onActivityResult method, but now that you said this something just occurred to me. I should mention that I'm implementing the rave API on a fragment, so when I put input the code you mentioned above the "protected' access modifier is highlighted as red, so I changed it to public. Do you think that could result in the error I'm getting? If so, how can I fix it?Thanks again.

**Comment by jeremiahVaris** [comment]
The onActivityResult needs to be in the activity housing the fragment, as that's where the result is sent.

**Comment by Arch-Unique** [comment]
I once had a problem like this, where i seriously needed ravepay to be on a fragment so i did something like this.

**Put The Below In Your Parent Activity** 
`@Override
    **protected** void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {

        for(Fragment fragment : getSupportFragmentManager().getFragments()){
            fragment.onActivityResult(requestCode, resultCode, data);
        }
    }`

**In your Fragment ,** 
`@Override
    **public** void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == RaveConstants.RAVE_REQUEST_CODE && data != null) {
            String message = data.getStringExtra("response");
            if (resultCode == RavePayActivity.RESULT_SUCCESS) {
                Log.i("result", message);
                Toast.makeText(getActivity(), "Transfer Successful ", Toast.LENGTH_LONG).show();
            }
            else if (resultCode == RavePayActivity.RESULT_ERROR) {
                Log.i("result", message);
                Toast.makeText(getActivity(), "ERROR " + message, Toast.LENGTH_LONG).show();
            }
            else if (resultCode == RavePayActivity.RESULT_CANCELLED) {
                Log.i("result", message);
                Toast.makeText(getActivity(), "CANCELLED " + message, Toast.LENGTH_LONG).show();
            }
        }
        else {
            Log.i("result", "there is serious error");
            super.onActivityResult(requestCode, resultCode, data);
        }
    }`

**Comment by maykhid** [comment]
Thanks alot... I previously did something like this but I took a longer route, though it worked I think implementing this is much better.

**Comment by maykhid** [comment]
Thanks @jeremiahVaris at first I didn't understand your last comment, but now I do.
