### ISSUE TITLE
App Crashes On Input Of Integer greater than 1 in Expiry Section of Card Fragment

### ISSUE THREAD

**Issue by Arch-Unique** [Flutterwave/rave-android#149]
## In the Expiry date section of the card fragment, when a user inputs a number other than 1 or 0 it crashes. (CardFragment.java Line 662)

I saw the source code and i noticed that the String cardExpiryToSet adds "/" to a one digit number and as its parses the string to an int, it meets "/" and does not know what to do with it -(Number format exception to be exact).

## System Information

 - Operating system: Android 7
 - Rave version: 1.0.42

## Suggestion In Fixing It

![ChangeAndroid](https://user-images.githubusercontent.com/57495668/68404617-c02a7c80-0176-11ea-90f2-8f0f44b07dc9.png)

**Comment by jeremiahVaris** [comment]
Thank you for this @Arch-Unique.

**Comment by biodunalfet** [comment]
This will be fixed in the next update.
