### ISSUE TITLE
compliance Required. please contact support

### ISSUE THREAD

**Issue by Nsikaktopdown** [Flutterwave/rave-android#15]
i am having this error when trying to pay

**Comment by biodunalfet** [comment]
Staging or live?

**Comment by Nsikaktopdown** [comment]
I got the keys from here https://ravepay.co. I guess it live

**Comment by biodunalfet** [comment]
Did you set `.isStaging()` to true in the initialization stage in code? Also check if your keys are live or staging keys on the ravepay.co dashboard

**Comment by Nsikaktopdown** [comment]
Hello @biodunalfet  How will i know its a live key?

**Comment by temiadesina** [comment]
Hi @Nsikaktopdown when you sign up on https://ravepay.co you are set to our production/live environment, which means keys gotten from there are live. To get staging keys, kindly sign up on our sandbox environment http://rave.fronendpwc.com and set `.onStagingEnv(true)` in your app, this would put you in the sandbox mode on the sdk.
