### ISSUE TITLE
Main page is rendering wrongly

### ISSUE THREAD

**Issue by lalesan** [Flutterwave/rave-android#152]
After initialize RavePayManager, if the user click in whatever payment method, the element is replicated in all screen
![Captura de pantalla de 2019-11-26 16-08-19](https://user-images.githubusercontent.com/723457/69650770-016fc700-1067-11ea-9b62-5d86e6ac8ca9.png)

**Comment by jeremiahVaris** [comment]
Hi @lalesan, this seems to be on an emulator. Please, can you try on another device and share what happens then. Also, it would really help fast track the debugging if you could share this information:

- Your initialization code.
- The android version of the emulator this issue occurred on.
- The version of the SDK you're using.

**Comment by lalesan** [comment]
Hi @jeremiahVaris. Yesterday I tried with a real device and it happens also. 
With 
* Initialization code:
        new RavePayManager(getActivity()).setAmount(amount)
                .setCountry(country)
                .setCurrency(currency)
                .setEmail(email)
                .setPublicKey(publicKey)
                .setEncryptionKey(encryptionKey)
                .setTxRef(referenceId)
                .acceptAccountPayments(true)
                .acceptCardPayments(true)
                .acceptGHMobileMoneyPayments(country.equals("GH"))
                .acceptBankTransferPayments(true)
                .acceptUssdPayments(true)
                .onStagingEnv(isDevBuild())
                .withTheme(R.style.FlutterwaveTheme)
                .showStagingLabel(isDevBuild())
                .initialize();
* android version tested: 
    - 9 in emulator
    - 9 in real device
    - 4.4.2 in emulator
    - 8 in emulator
* sdk version: 26.1.1

**Comment by jeremiahVaris** [comment]
Thanks for your response @lalesan. I tried reproducing this on my end, but it works fine. If you don't mind, could we please get on a video call, so we can share screens and possibly debug this together?

**Comment by lalesan** [comment]
Sure. By skype for example? I can use your email from your github profile

**Comment by jeremiahVaris** [comment]
Yes, please. You can join here: https://join.skype.com/jPu35TtTBmkz

**Comment by biodunalfet** [comment]
@lalesan can you share the content of your styles.xml file?
