### ISSUE TITLE
cellotto

### ISSUE THREAD

**Issue by shashi125** [Flutterwave/rave-android#16]
java.lang.NoSuchFieldError: No static field permission_required_layout of type I in class Lcom/flutterwave/raveandroid/R$id; or its superclasses (declaration of 'com.flutterwave.raveandroid.R$id' appears in /data/app/company.cell.com.cellotto-2/base.apk:classes7.dex)

please help me, i am facing this problem.

**Comment by biodunalfet** [comment]
What version of the sdk are you using?

**Comment by shashi125** [comment]
rave-android:1.0.6

**Comment by biodunalfet** [comment]
Use `compile 'com.github.Flutterwave:rave-android:1.0.10'`

**Comment by shashi125** [comment]
again same problem occured.

**Comment by shashi125** [comment]
anybody is there. please help me

**Comment by shashi125** [comment]
anybody is there.

**Comment by biodunalfet** [comment]
@shashi125 okay. This error means you have a layout in your project with the name `permission_required_layout.xml`. You'll have to rename that file
