### ISSUE TITLE
Zambia Mobile Money

### ISSUE THREAD

**Issue by ilikewebsite** [Flutterwave/rave-android#166]
In ZM Mobile Money MTN Network uses *303# but its showing *170#
which fails the transaction

**Comment by bolaware** [comment]
Is this still happening for you @ilikewebsite, Let us know please. So sorry for our so-so late reply.

**Comment by ilikewebsite** [comment]
> Is this still happening for you @ilikewebsite, Let us know please. So sorry for our so-so late reply.

Do you really think anyone can wait for 7 Months with this ?
