### ISSUE TITLE
runtime error when sdk loaded

### ISSUE THREAD

**Issue by mayurrathod27** [Flutterwave/rave-android#167]
![Screenshot_1](https://user-images.githubusercontent.com/60100584/72729555-63efca00-3bb5-11ea-9652-aada1c1c7acc.png)

## System Information

 - Operating system:
 - Rave version:

**Comment by mikelis135** [comment]
Hello mayurrathod27, 

Can you please share more details of the problem, you seem to have gradle errors

**Comment by mayurrathod27** [comment]
> Hello m
![Screenshot_2](https://user-images.githubusercontent.com/60100584/72776386-0c467280-3c38-11ea-89ff-152a992884b8.png)
ikelis135,
> 
> Yes sure . Please Check image when i run the project it shows these types of error

**Comment by mikelis135** [comment]
Hii @mayurrathod27 , the actual dependency causing this error is the lombok library from your gradle errors.

You can downgrade the library to version 1.16.18 to solve the problem

You can check this, if problem persists
https://github.com/rzwitserloot/lombok/issues/1882

Also, you seem to have Picasso issues, if you have the Picasso library in your gradle, check this 

https://stackoverflow.com/questions/47844478/cannot-find-symbol-method-with-using-picasso-library-android/47844490

and also restart your android studio to fix this error


We hope you'll find integrating flutterwave's Rave library seamless and don't hesitate to reply if you have any issues concerning our payment library.

Thanks

**Comment by mayurrathod27** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/60100584/72786491-ba134a80-3c53-11ea-9b18-4f78bbb2c8fa.png)

hello @mikelis135 

i was done four time invalidate cache and restart studio.

and above screenshot i was tested with lombok 1.16.18 also but error occurring same .

Picasso Library has not error because when i remove "implementation 'com.github.Flutterwave:rave-android:1.0.48'"  dependency Picasso doesn't get error when i put flutter wave dependency then it errors are occur.

Please Find Some Solution As soon as Possible.

**Comment by mikelis135** [comment]
Hello @mayurrathod27 ,
I have created a sample project here which include all your gradle libraries and implements **Rave and picasso**

i commented 
implementation 'com.splunk.mint:mint:5.0.0' and
implementation(name: 'sinch-android-rtc', version: '+', ext: 'aar') as i could not pull the sdk

https://github.com/mikelis135/GradleTest

**Comment by mayurrathod27** [comment]
Hello @mikelis135 

all gradle built successfully but when i generate release or build apk it shows error.

If i remove flutterwave library this error was gone. 

![Screenshot_1](https://user-images.githubusercontent.com/60100584/73131623-975aaa80-4034-11ea-8042-5354f0231e8c.png)

**Comment by mikelis135** [comment]
Hello @mayurrathod27 

https://developer.android.com/studio/build/dependencies#duplicate_classes contains the solution you require.

It appears this okhttp logger conflicts (most likely version) with the rave sdk. You can fix this error by making the okhttp logging interceptor the same version as the version in the sdk which is 3.9.1

You can also try to exclude the duplicate okhttp library from the rave android sdk to use yours

Or add a resolution strategy to your gradle

Finally, the last option is to enable desugaring using this
android.enableD8=true
