### ISSUE TITLE
charge not yet supported for country nigeria

### ISSUE THREAD

**Issue by solokingjec** [Flutterwave/rave-android#17]
I am trying rave and am getting this error.

**Comment by nmeri17** [comment]
Please, how did you solve this? I've been on this for almost three days. Tried with different accounts and keys, no success.

**Comment by biodunalfet** [comment]
@nmeri17 are you passing country as Nigeria or "NG"?

**Comment by nmeri17** [comment]
I tried that in combination with keys from another account and it went
through. Thank you, Hamza.
