### ISSUE TITLE
App Crashes with "No static field rave_pinButton of type I"

### ISSUE THREAD

**Issue by Presheda** [Flutterwave/rave-android#170]
in staging environment, when i attempt to make payment, the app crashes.
i notice this error only occur with some specific test cards. 

**5531 8866 5214 2950
cvv 564
Expiry: 09/22
Pin 3310
otp 12345**

![Screenshot (8)](https://user-images.githubusercontent.com/26353504/75425341-ccfbf780-5942-11ea-818e-d882e628a0a6.png)

**Comment by bolaware** [comment]
Hello @Presheda , i think you have a layout called fragment_pin.xml in your project which lead to this error, kindly rename it, try again and see if it works. If it does we will have to make our layouts names more unique in the next release.

**Comment by Presheda** [comment]
Thank you for the reply.
i didn't actually have a layout named **fragment_pin**, instead i have a layout named **pin_layout**.
When i open the **fragment_pin** of the sdk, it included another layout named **pin_layout**.
In all, the **fragment_pin** was inflating my **project's pin_layout** instead of the **sdk pin_layout**.
so i am guessing this error would still occur when i have layout named **fragment_pin or pin_layout.**

i have renamed my layout for peace to reign.
