### ISSUE TITLE
When try to charge the saved card and put the otp 12345 then its sending invalid OTP

### ISSUE THREAD

**Issue by akbarattar3** [Flutterwave/rave-android#172]
## System Information

 - Operating system:
 - Rave version:

**Comment by akbarattar3** [comment]
When try to charge the saved card throwing me invalid otp error

**Comment by jeremiahVaris** [comment]
@akbarattar3 is this on live or staging?

**Comment by akbarattar3** [comment]
This is staging environment

**Comment by jeremiahVaris** [comment]
Saved card charge is not currently functional for staging. Please test with a live card.

**Comment by akbarattar3** [comment]
How to test whether its working ?

**Comment by akbarattar3** [comment]
Can I get the token for stored card ?

**Comment by jeremiahVaris** [comment]
The save card feature on the SDK a bit different from card tokenization, in that the user will still need to authenticate. The token is not provided.

**Comment by akbarattar3** [comment]
Okay so from app only we can charge the user , no way for charging from backend by storing the cards ?yeah ?

**Comment by jeremiahVaris** [comment]
@akbarattar3 Kindly see the documentation on [saving a card](https://developer.flutterwave.com/v2.0/reference#save-a-card).
