### ISSUE TITLE
Rave Android drop in UI error

### ISSUE THREAD

**Issue by olofumark** [Flutterwave/rave-android#173]
java.lang.RuntimeException: Unable to start activity ComponentInfo{ng.streetpay.streetpay/com.flutterwave.raveandroid.RavePayActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(19466): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
E/AndroidRuntime(19466): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
E/AndroidRuntime(19466): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/AndroidRuntime(19466): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
E/AndroidRuntime(19466): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime(19466): 	at android.os.Looper.loop(Looper.java:203)
E/AndroidRuntime(19466): 	at android.app.ActivityThread.main(ActivityThread.java:6251)
E/AndroidRuntime(19466): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19466): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
E/AndroidRuntime(19466): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
E/AndroidRuntime(19466): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(19466): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:696)
E/AndroidRuntime(19466): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
E/AndroidRuntime(19466): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552)
E/AndroidRuntime(19466): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
E/AndroidRuntime(19466): 	at com.flutterwave.raveandroid.RavePayActivity.onCreate(RavePayActivity.java:104)
E/AndroidRuntime(19466): 	at android.app.Activity.performCreate(Activity.java:6666)
E/AndroidRuntime(19466): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
E/AndroidRuntime(19466): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
E/AndroidRuntime(19466): 	... 9 more

**Comment by jeremiahVaris** [comment]
Hi @olofumark, please what Theme are you using?

**Comment by olofumark** [comment]
Here is it.    
<style name="FlutterwaveTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="OTPButtonStyle">@style/otpBtnStyle2</item>
        <item name="PayButtonStyle">@style/payBtnStyle2</item>
        <item name="OTPHeaderStyle">@style/otpHeaderStyle2</item>
        <item name="TabLayoutStyle">@style/tabLayoutStyle2</item>
        <item name="PinHeaderStyle">@style/pinHeaderStyle2</item>
        
    </style>

**Comment by bolaware** [comment]
@olofumark Please use this 
```
<style name="TestNewTheme" parent="AppTheme.NoActionBar">
        <item name="colorPrimary">#092342</item>
        <item name="colorPrimaryDark">#b71c1c</item>
        <item name="colorAccent">#7cb342</item>
        <item name="OTPButtonStyle">@style/otpBtnStyle2</item>
        <item name="PayButtonStyle">@style/payBtnStyle2</item>
        <item name="OTPHeaderStyle">@style/otpHeaderStyle2</item>
        <item name="TabLayoutStyle">@style/tabLayoutStyle2</item>
        <item name="PinHeaderStyle">@style/pinHeaderStyle2</item>
        <item name="SavedCardButtonStyle">@style/svdCardsBtnStyle2</item>
        <item name="PaymentTileStyle">@style/newPaymentTileStyle</item>
        <item name="PaymentTileTextStyle">@style/newPaymentTileTextStyle</item>
        <item name="PaymentTileDividerStyle">@style/newPaymentTileDividerStyle</item>
    </style>

    <style name="newPaymentTileTextStyle">
        <item name="android:textColor">#4a4a4a</item>
    </style>

    <style name="newPaymentTileDividerStyle">
        <item name="android:textColor">#4a4a4a</item>
    </style>

    <style name="newPaymentTileStyle">
        <item name="android:background">#99f9a825</item>
    </style>

    <style name="pinHeaderStyle2">
        <item name="android:background">#37474f</item>
    </style>

    <style name="otpBtnStyle2" parent="@android:style/Widget.Button">
        <item name="android:background">@drawable/otp_button_curved</item>
        <item name="android:textColor">#009688</item>
    </style>

    <style name="svdCardsBtnStyle2" parent="@android:style/Widget.Button">
        <item name="android:background">@drawable/blue_btn_curved</item>
        <item name="android:textColor">#039be5</item>
    </style>

    <style name="payBtnStyle2" parent="@android:style/Widget.Button">
        <item name="android:background">@drawable/green_btn_curved</item>
        <item name="android:textColor">#bcaaa4</item>
    </style>
```
and add it to Rave with .withTheme(R.style.TestNewTheme). You can change the colours as you will. Please learn more by looking at the test app in the repo

**Comment by olofumark** [comment]
@bolaware thanks but that didn't work. I still get the same error.

**Comment by olofumark** [comment]
I have tried also commenting out //.withTheme(R.style.TestNewTheme) just to see the default UI work but it didn't.
