### ISSUE TITLE
How can I set amount to a String

### ISSUE THREAD

**Issue by ChocoTVng** [Flutterwave/rave-android#184]
Everything is actually working great.. kudos to your work...
I created an e-commerce app.. and the total amount of product is a string.. how do I pass the string to  set.Amount

**Comment by biodunalfet** [comment]
Hi. You can convert it to double using `Double.parseDouble(your string amount)` if you're using java. 

For Kotlin, you can simply do `"your string amount".toDouble()`

**Comment by ChocoTVng** [comment]
Thanks I've solved it.. it's now working fine... God bless
