### ISSUE TITLE
My Action bar wont go away 

### ISSUE THREAD

**Issue by Justicea83** [Flutterwave/rave-android#187]
My actionbar wont go away even though i set the theme correctly.
![Capture](https://user-images.githubusercontent.com/26106822/83353396-417f7180-a34a-11ea-8b08-9022e3e3a6a6.PNG)
![Capture-1](https://user-images.githubusercontent.com/26106822/83353400-45ab8f00-a34a-11ea-8127-3764d805cea9.PNG)
![Capture-3](https://user-images.githubusercontent.com/26106822/83353401-480de900-a34a-11ea-9825-2d459c968b08.PNG)

**Comment by bolaware** [comment]
Thanks for bringing this our attention to this, we have released version 2.0.2 to solve your issue. Lets know if it works for you.

**Comment by Justicea83** [comment]
Yes its fixed thanks
