### ISSUE TITLE
VerificationActivity crash on verification

### ISSUE THREAD

**Issue by JovanDon** [Flutterwave/rave-android#191]
Application crashes when method verificationUtils.showWebpageVerificationScreen(authenticationUrl) is called. (Dependency 'com.github.Flutterwave.rave-android:rave_presentation:2.0.4'  )

## Describe the Bug
The application crashes with exit and flags an error " android.content.ActivityNotFoundException: Unable to find explicit activity class {com.cabral.foodwallet/com.flutterwave.raveutils.verification.VerificationActivity}; have you declared this activity in your AndroidManifest.xml?" 

## System Information
 - Operating system:
Linux /Android studio 4.0
 - Rave version:
com.github.Flutterwave.rave-android:rave_presentation:2.0.4

**Comment by jeremiahVaris** [comment]
@JovanDon 
This has been fixed now. Please upgrade to version `2.0.5`.
