### ISSUE TITLE
I dont get Pay with Account option when my Currency is USD even after setting the acceptAccountPayments as true

### ISSUE THREAD

**Issue by MaheshwariSneha27** [Flutterwave/rave-android#193]
when my Currency is NGN  i get the option for pay with account and when its USD I get only pay with cards 
I also checked with sample provide it also works the same.
 
Below is the code i have used
new RaveUiManager(this)
                    .setAmount(Double.parseDouble(amount))
                 
                    .setCurrency(currency)
                    .setEmail(email)
                    .setfName(firstName)
                    .setlName(lastName)
                    .setNarration(narration)
                    .setPublicKey(BaseActivity.KEY_RAVE_PUBLIC)
                    .setEncryptionKey(BaseActivity.KEY_RAVE_ENCRYPTION)
                    .setTxRef(txRef)
                    .allowSaveCardFeature(true)
                    .shouldDisplayFee(true)
                    .acceptMpesaPayments(false)
                    .acceptAccountPayments(true)
                    .acceptCardPayments(true)
                    .acceptAchPayments(false)
                    .acceptUkPayments(true)
                    .acceptUssdPayments(true)
          
                    .acceptGHMobileMoneyPayments(false)
                    .acceptUgMobileMoneyPayments(false)
                    .acceptBankTransferPayments(true)
                    .onStagingEnv(true)
                    .showStagingLabel(true)
                
                    .initialize();

**Comment by jeremiahVaris** [comment]
Hi @MaheshwariSneha27 , for USD account charge, what you need is `acceptAchPayments(true)`.
