### ISSUE TITLE
This issue is still disturbing our app in production

### ISSUE THREAD

**Issue by mugabi0978** [Flutterwave/rave-android#196]
- Latest version
- Live
- GHS

But was fixed; it looked like there was a limit on the currency in production.
#Our wallet limits were increase but issue resumed today.

_Originally posted by @mugabi0978 in https://github.com/Flutterwave/rave-android/issues/194#issuecomment-642237918_

**Comment by jeremiahVaris** [comment]
Hi @mugabi0978, please share your business name with hi@flutterwavego.com asking for limit increase. The compliance team will direct on how to proceed.
