### ISSUE TITLE
Slack community link in docs inactive

### ISSUE THREAD

**Issue by bot101** [Flutterwave/rave-android#202]
Following the Slack community link in the docs displays a message that says that the link has become inactive. Is there any other means by which one can join the slack channel if it is still functional?

**Comment by bolaware** [comment]
Hello @bot101, here goes the link https://join.slack.com/t/flutterwavedevelopers/shared_invite/zt-7mdxu82t-~WwizwN3eWKjUXLY275AzQ. Sorry for the late response

**Comment by bot101** [comment]
thanks @bolaware
