### ISSUE TITLE
Ghana Mobile Money Payment UI

### ISSUE THREAD

**Issue by cyphasusu** [Flutterwave/rave-android#203]
The button for Pay happens to appear on top of "select network" label.
You might want to check the design and rectify that.
<img width="394" alt="Screenshot 2020-06-24 at 6 26 02 PM" src="https://user-images.githubusercontent.com/26836241/85612245-374e4b80-b648-11ea-88a2-802797f7b4e8.png">

**Comment by jeremiahVaris** [comment]
Thanks for bringing this to our notice. It's been fixed now in release `2.0.8`.

**Comment by entcomputing** [comment]
Thanks for the quick response @jeremiahVaris

**Comment by cyphasusu** [comment]
Thanks for the quick response @jeremiahVaris
