### ISSUE TITLE
Lint test ---  Error: Invalid package reference in library; not included in Android: javax.inject. Referenced from com.flutterwave.raveandroid.rave_core.di.DeviceIdGetterModule_Factory. [InvalidPackage]

### ISSUE THREAD

**Issue by AmosKorir** [Flutterwave/rave-android#207]
I am using the SDK for card payment only. It is fine but the lint test would not pass. I assume there are used references.

**Comment by bolaware** [comment]
Hello @AmosKorir , I tried running `./gradlew lint` command but no error came up, however I did a blind fix to what i think might be the issue - Use this `com.github.bolaware:rave-android:2.0.9` and let us know. Thanks
