### ISSUE TITLE
Not working with International cards.

### ISSUE THREAD

**Issue by kennyshittu** [Flutterwave/rave-android#21]
After upgrading to the latest version, our users are unable to make payment using international cards. FWIW, this was working before. 

Error message : `Unknown Auth model`
And I believe it has to do with the recent changes here https://github.com/Flutterwave/rave-android/blob/master/raveandroid/src/main/java/com/flutterwave/raveandroid/card/CardPresenter.java#L75

I tested on staging using the flutterwave intl. test cards and  got the same error : 

Test VisaCard (International)
4556052704172643
cvv: 899
Expiry: 01/19

Test American Express Card (International)
344173993556638
cvv: 828
Expiry: 01/18

Please, kindly take a quick look as it's affecting a high percentage of our users.

**Comment by andela-Kshittu** [comment]
@biodunalfet Please take a look as soon as you can.

**Comment by farsheel** [comment]
i got the same problem, please take a look as soon as possible

**Comment by biodunalfet** [comment]
Hi @andela-Kshittu and @farsheel, sorry I'm just responding, I'll investigate and get back to you in a few hours.

**Comment by Abdulr-intija** [comment]
Hi @andela-Kshittu ,
By the way, is your project ProGuard enabled? just asking

**Comment by andela-Kshittu** [comment]
@biodunalfet Thanks

**Comment by devendroid** [comment]
I'm getting same issue. and when trying 1.0.8
getting ERROR: Failed to resolve: com.github.Flutterwave:rave-android:1.0.18,
I also tried with today latest version 1.0.35, 
But still getting Unknown Auth Model. ....?
