### ISSUE TITLE
Error message: please provide one of tx Ref or flw Ref; data null

### ISSUE THREAD

**Issue by gabbyvan** [Flutterwave/rave-android#211]
I have integrated flutterwave successfully into my current project but whenever I make a live payment it throws this toast error message but when i check my rave dashboard the payment is successful. The paid amount, the generated txRef transaction ID from the app correctly displays in the payment details for the transaction in the dashboard so I know the txRef wasn't null. And the payment UI closes and returns to the previous activity 
![Screenshot_20200630-105322_Adwadifo Adanfo](https://user-images.githubusercontent.com/64509770/86188171-4d1ead80-bb2d-11ea-876e-2364cff338b2.jpg)

**Comment by jeremiahVaris** [comment]
Hi @gabbyvan 
Thanks for raising this.
Please share what version of the Flutterwave SDK you're using.

**Comment by gabbyvan** [comment]
It is the 2.0.5 version of your SDK

**Comment by jeremiahVaris** [comment]
@gabbyvan 
Please update to the latest version: `2.0.9`

**Comment by gabbyvan** [comment]
Now error it says an error occured while attempting to decrypt some parameters. It doesn't really specify which parameters are those please
