### ISSUE TITLE
Android app theme change 

### ISSUE THREAD

**Issue by rohitsinglailluminz** [Flutterwave/rave-android#215]
I am facing very weird issue -
For sdk implementation 'com.github.Flutterwave.rave-android:rave_android:2.1.1'

On some devices my theme colors have been updated automatically just by adding dependency.

But on using sdk implementation 'com.github.Flutterwave.rave-android:rave_android:2.0.9'

it is working good.

**Comment by bolaware** [comment]
Can you give more context, are you passing a theme into the sdk, post it here and whats the colours changes in screenshots?

**Comment by rohitsinglailluminz** [comment]
@bolaware , not passign any theme into sdk, i have just added the dependency and this issue occurred.

This is what we want.
![image](https://user-images.githubusercontent.com/50132109/87795046-25398480-c865-11ea-8626-8d03c2db339c.png)

But after adding dependency, updated to this.
![image](https://user-images.githubusercontent.com/50132109/87795111-36829100-c865-11ea-95df-b3212fdbf07b.png)

Tested on devices -
One plus 6
Redmi note 7
Lenovo k8 plus

**Comment by bolaware** [comment]
@rohitsinglailluminz check this out for this fix com.github.bolaware.rave-android:rave_android:2.1.5

**Comment by MaheshwariSneha27** [comment]
> I am facing very weird issue -
> For sdk implementation 'com.github.Flutterwave.rave-android:rave_android:2.1.1'
> 
> On some devices my theme colors have been updated automatically just by adding dependency.
> 
> But on using sdk implementation 'com.github.Flutterwave.rave-android:rave_android:2.0.9'
> 
> it is working good.

**Comment by MaheshwariSneha27** [comment]
HI 

I am also facing the same issue my device theme color changes with the new sdk and is working fine with 2.0.9

**Comment by rohitsinglailluminz** [comment]
Hi @bolaware , tried with this - com.github.bolaware.rave-android:rave_android:2.1.5
issue not resolved.

**Comment by bolaware** [comment]
What device are you using, @MaheshwariSneha27?

**Comment by bolaware** [comment]
@rohitsinglailluminz Can we get on an hangout call to have a look at your setup?  I can't replicate it.

**Comment by MaheshwariSneha27** [comment]
Redmi note 5 pro

________________________________

**Comment by rohitsinglailluminz** [comment]
HI @bolaware ,you can connect with me on my hangout id - rohit.s@illuminz.com

**Comment by rohitsinglailluminz** [comment]
Hi @bolaware , anybody looking over this issue ?

**Comment by bolaware** [comment]
I sent you an invite @rohitsinglailluminz, if the time is suitable lets do it, if its not let me know when is suitable. Thanks

**Comment by bolaware** [comment]
@rohitsinglailluminz please try com.github.bolaware.rave-android:rave_android:2.1.8 this out. Thanks

**Comment by rohitsinglailluminz** [comment]
@bolaware , in sdk version - com.github.bolaware.rave-android:rave_android:2.1.8

I am getting this issue - "How would you like to pay?" label is not visible in some devices. 
PFA screenshot

![Screenshot_20200724-102203](https://user-images.githubusercontent.com/50132109/88361775-c8bff300-cd97-11ea-8354-e04591f49130.png)

and also this is still showing bank account background in dark theme.
![Screenshot_20200724-102156](https://user-images.githubusercontent.com/50132109/88361837-0cb2f800-cd98-11ea-8ed3-d4ba383fc8ca.png)

**Comment by bolaware** [comment]
When you are initializing the sdk, you are passing a theme style, kindly post the style here @rohitsinglailluminz

**Comment by rohitsinglailluminz** [comment]
@bolaware , i am passing this theme style - 
    <style name="RaveDesignTheme" parent="AppTheme.NoActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="OTPButtonStyle">@style/ButtonBlueStyle</item>
        <item name="PayButtonStyle">@style/ButtonBlueStyle</item>
        <item name="OTPHeaderStyle">@style/otpHeaderStyle2</item>
        <item name="TabLayoutStyle">@style/tabLayoutStyle2</item>
        <item name="PinHeaderStyle">@style/pinHeaderStyle2</item>
    </style>

**Comment by bolaware** [comment]
For this new version, you will have to change 'AppTheme.NoActionBar' to 'RaveAppTheme.NoActionBar' @rohitsinglailluminz

**Comment by rohitsinglailluminz** [comment]
@bolaware for sdk-  com.github.bolaware.rave-android:rave_android:2.1.8 
It is working good now at my end.

**Comment by bolaware** [comment]
Thanks. Merged now for com.github.Flutterwave.rave-android:rave_android:2.1.5 #218
