### ISSUE TITLE
When paying with account the receipt generated has anonymous customer 

### ISSUE THREAD

**Issue by MaheshwariSneha27** [Flutterwave/rave-android#217]
new RaveUiManager(this)
                    .setAmount(Double.parseDouble(selectAmount))
                    .setCurrency(inCurrency)
                    .setEmail(userEmail)
                    .setfName("Sneha")
                    .setlName("Maheshwari")
                    .setNarration(narration)
                    .setPublicKey(BaseActivity.KEY_RAVE_PUBLIC)
                    .setEncryptionKey(BaseActivity.KEY_RAVE_ENCRYPTION)
                    .setTxRef(txRef)
                    .allowSaveCardFeature(true)
                    .shouldDisplayFee(true)
                    .acceptUssdPayments(true)
                    .acceptMpesaPayments(false)
                    .acceptAccountPayments(true)
                    .acceptCardPayments(true)
                    .acceptAchPayments(false)
                    .acceptGHMobileMoneyPayments(false)
                    .acceptUgMobileMoneyPayments(false)
                    .acceptBankTransferPayments(true)
                    .onStagingEnv(true)
                    .showStagingLabel(true)
                    .initialize();

above is the code I have used to initialize Rave.

When I pay with card I get all the deatils of the user but when I pay with account I only get email id of the User and in the fullname I get "Anonymous customer"

**Comment by jeremiahAI** [comment]
This issue has now been fixed in `2.1.3`. Please upgrade.
