### ISSUE TITLE
 class file for androidx.fragment.app.Fragment not found

### ISSUE THREAD

**Issue by chuksdsilent** [Flutterwave/rave-android#220]
I am trying to implement flutterwave on my android but I am getting this error:

new RaveUiManager(this).setAmount(100);
        ^
 class file for androidx.fragment.app.Fragment not found

My system info
windows 10
android studio 4.0
gradle: 6.1.1

**Comment by bolaware** [comment]
You have to migrate your project to AndroidX to use the sdk. See this part of README where it is stated [here](https://github.com/Flutterwave/rave-android#requirements) and how you can migrate
