### ISSUE TITLE
AAPT: error: resource attr/foregroundGravity (aka com.example.system2.tranxav:attr/foregroundGravity) not found.  

### ISSUE THREAD

**Issue by chuksdsilent** [Flutterwave/rave-android#222]
I am trying to implement your sdk on my android app but I am getting this error
AAPT: error: resource attr/foregroundGravity (aka com.example.system2.tranxav:attr/foregroundGravity) not found.
 
My operating system is windows 10
android studio is 4.0.1
gradle is 6.6

What could be the cause? Thanks

**Comment by bolaware** [comment]
This is not the sdk error, @chuksdsilent. It's something from your end. Have you migrated your app to AndroidX?
