### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by myKidzDay** [Flutterwave/rave-android#223]
Hi Team , 
I am using the android sdk. But i am getting this error with the TestCard. Can you please share what i have missing
![Screenshot_20200830-140111_Dracta_20200830_140558081](https://user-images.githubusercontent.com/19366880/91654855-01a36400-eaca-11ea-844e-ba30cdfb93d9.jpg)

**Comment by jeremiahAI** [comment]
Hi @myKidzDay , please ensure you're passing the txRef and email to the SDK. To be sure, hardcode the values and test again.
