### ISSUE TITLE
Amount is required Toast

### ISSUE THREAD

**Issue by neri4488** [Flutterwave/rave-android#227]
## Bug Description
When I attempt to pay by Uganda Mobile Money, I pass the amount in the builder.

I put the mobile money number and click Pay.

It then shows a pop dialog with the amount and I click yes.

Then a toast shows up "Amount is required", this is the bug because the amount is already provided.

## System Information

 - Operating system: Android 8.1.0
 - Rave version: rave_android:2.1.8

## Additional Context
Am using a pre-build UI, with no any customization
Check image here:
![Screenshot_20200919-185736](https://user-images.githubusercontent.com/11741247/93671406-722b1880-faab-11ea-8d10-49012d509e6f.png)

**Comment by jeremiahAI** [comment]
@neri4488 
Please ensure that you're using the correct encryption key in your setup. Take note that it should be the encryption key and not the secret key.

**Comment by neri4488** [comment]
> 
> 
> @neri4488
> Please ensure that you're using the correct encryption key in your setup. Take note that it should be the encryption key and not the secret key.

Thanks @jeremiahAI 
I have a public key and a secret key, where do I find the encryption key?

**Comment by jeremiahAI** [comment]
@neri4488 
The encryption key can be found in the [API tab](https://dashboard.flutterwave.com/dashboard/settings/apis) of your settings page on your dashboard.

**Comment by neri4488** [comment]
Well, got it. Thanks @jeremiahAI
