### ISSUE TITLE
Keep getting  unexpected response code for connect: 503

### ISSUE THREAD

**Issue by EjilolaHammedEjitomiwa** [Flutterwave/rave-android#228]
## Describe the Bug
Have been building my project using Rave sdk but sometimes I used to get this message as response
unexpected response code for connect: 503""

## System Information

 - Operating system: Windows
 - Rave version:  2.1.8

**Comment by jeremiahAI** [comment]
@EjilolaHammedEjitomiwa 
Please provide some more context on how to reproduce this error, and what actions you take that leads to the error.

**Comment by EjilolaHammedEjitomiwa** [comment]
After initializing the RaveUiManager, to select payment options (card, account etc) for example card payment, after the filling the details to start the payment process, onClick of the pay button I got the error message

**Comment by jeremiahAI** [comment]
@EjilolaHammedEjitomiwa 
Please confirm if you're still experiencing this. Also confirm if it's live or on staging.

**Comment by EjilolaHammedEjitomiwa** [comment]
Nope I haven't face it for some time now and it is staging mode by the way

**Comment by jeremiahAI** [comment]
It seems to have been a temporary server error. I've not been able to replicate it here. I'll be closing this issue now. You should be able to test properly now. If you start experiencing this again, kindly let me know.
