### ISSUE TITLE
TX REF is null

### ISSUE THREAD

**Issue by egesamichael** [Flutterwave/rave-android#229]
Trying out the SDK but keep getting an Error. "Please provide one of the tx ref or flw ref","data":null. yet i have added .setTxRef("MyTransactionRef")

**Comment by jeremiahAI** [comment]
@egesamichael 
What payment method are you trying with?

**Comment by egesamichael** [comment]
Uganda Mobile Money. Also note I get the OTP

**Comment by egesamichael** [comment]
![Screenshot_20200929-201330](https://user-images.githubusercontent.com/22357165/94591164-59331c00-0290-11eb-8e8a-11b1feab9110.png)

**Comment by jeremiahAI** [comment]
Hi @egesamichael 
Apologies for the delay, please what version of the SDK are you on?
Also please confirm if you've been able to go through with a successful transaction.

**Comment by egesamichael** [comment]
Hello @jeremiahAI 

I have this   implementation 'com.github.Flutterwave:rave-android:1.0.49.1'

**Comment by egesamichael** [comment]
![Screenshot_20201005-223558](https://user-images.githubusercontent.com/22357165/95123876-4c646b80-075b-11eb-9285-344744c08c30.png)
That's the error am getting

**Comment by jeremiahAI** [comment]
@egesamichael 
Please could you update to the latest version `2.1.8`. There've been a couple of updates since then.

**Comment by jeremiahAI** [comment]
@egesamichael 
Please could you update to the latest version `2.1.8`. There've been a couple of updates since then.

**Comment by egesamichael** [comment]
Thank you @jeremiahAI let me do that right away. Will update you

**Comment by egesamichael** [comment]
Hello @jeremiahAI it works fine. Thanks Hoping Bill payments for Uganda will be handled soon.
