### ISSUE TITLE
An error occurred while retrieving banks

### ISSUE THREAD

**Issue by Android234** [Flutterwave/rave-android#23]
Hello,

When we click on Banks edit text it called the api and in response it gives error with "An error occurred while retrieving banks". It was working before but suddenly it showing this error

**Comment by Android234** [comment]
Well I checked with the server, maybe some issue is there because I am not able to log in my account also

**Comment by biodunalfet** [comment]
@Android234 you're not able to login to your server? or the Rave Dashboard?
