### ISSUE TITLE
A serious issue detected

### ISSUE THREAD

**Issue by Nzosiama-Chinecherem** [Flutterwave/rave-android#231]
It's weird and need to be corrected because it will make it impossible for others to integrate the SDK.

**Comment by bolaware** [comment]
You didn't say any issue @Nzosiama-Chinecherem, What's the issue that is detected and is weird?

**Comment by Nzosiama-Chinecherem** [comment]
Please change the dependency from implementation 'com.github.Flutterwave.rave-android:2.1.10' 
to
implementation 'com.github.Flutterwave:rave-android:2.1.10'

There suppose to be colon(:) after Flutterwave not for(.)

**Comment by bolaware** [comment]
Thanks @Nzosiama-Chinecherem, our bad. It's corrected now.
