### ISSUE TITLE
Unable to add the dependency to new projects

### ISSUE THREAD

**Issue by KingMastana** [Flutterwave/rave-android#232]
For days now a new project I'm done with but left with a payment gateway can't use yours because it always reports "failed to resolve com.github...." anytime I sync the project but works if I comment out your dependency.
Please work on this ASAP so we can continue working.

**Comment by jeremiahAI** [comment]
Hi @KingMastana, 
I just tested this and it works fine. I, as well as other developers, are using the same dependency declaration.

Please check that you're adding the dependency correctly:
`implementation 'com.github.Flutterwave.rave-android:2.1.10'`

If you're still having issues after checking, kindly share the code for declaring the dependency in your gradle file.

**Comment by KingMastana** [comment]
Please create a new project and add to confirm. All using it for months now may not have that issue.

![IMG_20201028_162550](https://user-images.githubusercontent.com/40878648/97554144-4a926e80-19ce-11eb-805c-8480e571c81a.jpg)

**Comment by FredDominant** [comment]
Hi @KingMastana , check if this works for you `implementation 'com.github.Flutterwave.rave-android:rave_android:2.1.10'`

**Comment by Nzosiama-Chinecherem** [comment]
In the dependency line of code, remove the dot(.) after Flutterwave and put colon(:)
That is add the dependency below as your Flutterwave dependency  

implementation 'com.github.Flutterwave:rave-android:2.1.10'

The bug will disappear ones you add this.
Happy coding.

**Comment by KingMastana** [comment]
> In the dependency line of code, remove the dot(.) after Flutterwave and put colon(:)
> That is add the dependency below as your Flutterwave dependency
> 
> implementation 'com.github.Flutterwave:rave-android:2.1.10'
> 
> The bug will disappear ones you add this.
> Happy coding.

Thanks a lot @Nzosiama-Chinecherem and everyone who gave their suggestions. It's working now🔥🚀
