### ISSUE TITLE
I can't charge myself for the transaction fee

### ISSUE THREAD

**Issue by EmmanuelDav** [Flutterwave/rave-android#233]
I am having issues with taking charges for the transacting fee, even do I enabled **Charge me for the transaction fee** in my flutter wave Account settings.

![flutter wave ](https://user-images.githubusercontent.com/52932347/99885301-296f1780-2c34-11eb-97a6-f21115313116.png)

In the Screenshot the normal price should be 9000 but I got some extra charges which could potentially scare away users. 
#Android

**Comment by jeremiahAI** [comment]
Hey @EmmanuelDav , 
From your screenshot, it looks like this is a live transaction. If so, please share this and your business name with the team at hi@flutterwavego.com, they will be able to assist in resolving it for your account.

_PS: I redacted the screenshot from your post to preserve the card info._
