### ISSUE TITLE
Android 10 onActivityResult handling

### ISSUE THREAD

**Issue by mbobiosio** [Flutterwave/rave-android#234]
## Describe the Bug
onBackPressed (RavePayActivity.RESULT_CANCELLED) isn't triggered on Android 10.
Same bug happens with RESULT_SUCCESS and RESULT_ERROR so user is stuck on the RaveUI Screen

## System Information

 - Operating system: Android 10
 - Rave version: 2.1.10

## Additional Context

This was first noticed on an Android 10 Pixel 4 x86 emulator

**Comment by jeremiahAI** [comment]
Hi @mbobiosio , are you launching the SDK from a fragment or activity?

**Comment by mbobiosio** [comment]
Activity

**Comment by jeremiahAI** [comment]
Hi @mbobiosio 
Please share. your code for launching the sdk and handling the response.

Also, I've tested on Android 10 and I had no issues.

**Comment by jeremiahAI** [comment]
Hi @mbobiosio 
It's been 7 days and I've not received a response from you, so I'll assume the issue has been resolved. If you're still experiencing the issue, feel free to comment under this.

Cheers

**Comment by mbobiosio** [comment]
Hello @jeremiahAI unfortunately this issue hasn't been fixed. I'm facing the same issue on my Android 10 device. I'm sorry I've been heavily occupied by other things.
Maybe we could do a live session.

**Comment by mbobiosio** [comment]
Hi, looking forward to being able to get past this issue. It appears to be an API 29 issue

**Comment by jeremiahAI** [comment]
Hi @mbobiosio,
Kindly send me a mail [here](mailto:varisiv@gmail.com?subject=Flutterwave SDK Android 10 Result handling), or share how I can reach you, so we can set up a meet.
