### ISSUE TITLE
Otp goes through

### ISSUE THREAD

**Issue by chuksdsilent** [Flutterwave/rave-android#237]
I am developing and android app which I integrated you payment platform. I used ravenonui integration. I am using the test card to test my app. The issue is that when I use wrong otp the request is always successful. What could be the problem. Another question I want to ask is how do I get the pin when I am live. Thanks for your anticipated answer

**Comment by jeremiahAI** [comment]
Hi @chuksdsilent 
Please share what test card you made use of, and what version of the SDK you're on.

AS for the PIN, it's supposed to be supplied by the user into your app, after which you pass it to the SDK using `cardPaymentManager.submitPin(pin)`.

**Comment by chuksdsilent** [comment]
This is the test card I am using
Card number: 5531 8866 5214 2950
cvv: 564
Expiry: 09/32
Pin: 3310
OTP: 12345

but if I use something like 485948 as my otp it will still be successful. I dont know why

Secondly, how will the user get the pin to be supplied.

**Comment by jeremiahAI** [comment]
Hi @chuksdsilent 
Currently, the test cards you're using are being mocked to be successful.

If you want to simulate a failed transaction, please make use of this card:

Card number: 5258582054729020
CVV: 887
Expiry: 11/30

**Comment by chuksdsilent** [comment]
Thanks for your reply.
How will the user get the pin. Will it be supplied to the user via sms or what?
