### ISSUE TITLE
At what point does the api send otp to the user

### ISSUE THREAD

**Issue by chuksdsilent** [Flutterwave/rave-android#239]
I integrated flutterwave to my android app but I want to ask at what stage is the otp sent to the user?
Is it when the card is initialized or when the card is charged?
Thanks
CardPaymentManager cardPayManager = new CardPaymentManager(
   raveNonUIManager, CardPaymentCallback, SavedCardsListener);
   Card card = new Card(
                    "5531886652142950")
                    "12",
                    "22",
                    "123"
            ); // Test MasterCard PIN

    cardPayManager.chargeCard(card);

**Comment by jeremiahAI** [comment]
Hi @chuksdsilent 
The OTP is sent to the user after the charge is initiated, as a text message.

**Comment by chuksdsilent** [comment]
Do I need to call the chargeCard method after the user has entered otp.

**Comment by jeremiahAI** [comment]
No. You need to pass the otp to the `cardPaymentManager.submitOtp(otp)`
functuon
