### ISSUE TITLE
In Android "Invalid Public Key Passed"

### ISSUE THREAD

**Issue by umamahacse** [Flutterwave/rave-android#24]
Hi,
I have integrated flutterwave PG in my android app.In sandbox the payment working fine.But now i changes the sandbox to live and have updated the live public and private keys.
But while checking the payment using my live card it shows Invaild public key passed error.
Can any one help me.

**Comment by biodunalfet** [comment]
Hi @umamahacse check if you have set .onStagingEnv(false) and you're passing the correct public and private live keys
