### ISSUE TITLE
How do I check if the user card detail is correct?

### ISSUE THREAD

**Issue by chuksdsilent** [Flutterwave/rave-android#240]
I integrated ravenonuimanager in my android app. I want to know how to check if the user card details is correct before sending them otp.

**Comment by jeremiahAI** [comment]
You can use the ` Utils.isValidLuhnNumber()` helper function to validate that the format of the card number is an acceptable format. However, this doesn't mean that the card is a valid card.

Rest assured, however, that the OTP will only be sent after we have validated the card number on our end.
