### ISSUE TITLE
How do I get the response when successful

### ISSUE THREAD

**Issue by chuksdsilent** [Flutterwave/rave-android#241]
I integrated nonraveui on android app. I want to know how to get the response of the transaction in json. thanks.

**Comment by chuksdsilent** [comment]
It has been more than 12 hours and my question has not been answered.

**Comment by jeremiahAI** [comment]
Hey @chuksdsilent 
The NonUI module doesn't return the transaction response currently, only the status of the transaction. Could you please share the use case where you'd need the transaction JSON?

**Comment by chuksdsilent** [comment]
I need the json transaction the user input card details to know if the card details is correct or not and also when the user inputs pin to know whether the pin is correct or not. 

Thanks for the answer

**Comment by jeremiahAI** [comment]
Hi @chuksdsilent
You don't need to parse the json to check if there are wrong details passed. By overwriting `onError`, you get an error message which you can display to the customer when anything goes wrong with the transaction.
