### ISSUE TITLE
Attempt to invoke virtual method 'void com.flutterwave.raveandroid.rave_java_commons.Payload.setPin(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by chuksdsilent** [Flutterwave/rave-android#244]
I am getting this error if I call on collect pin after initializing card payment

Attempt to invoke virtual method 'void com.flutterwave.raveandroid.rave_java_commons.Payload.setPin(java.lang.String)' on a null object reference

                  RaveNonUIManager raveNonUIManager =
                        new RaveNonUIManager()
                                .setAmount(100)
                                .setTxRef("ksldjfiuyj")
                                .setEmail("my@email.com")
                                .setPublicKey("*********")
                                .setEncryptionKey("*********")
                                .setPhoneNumber("**********")
                                .initialize();

                cardPayManager = new CardPaymentManager(raveNonUIManager, StripePayment.this );
                card = new Card("******", "****", "****", "******"); // Test MasterCard PIN
                cardPayManager.chargeCard(card);

                pin_et = findViewById(R.id.pin_et);
                String pin = pin_et.getText().toString();
                cardPayManager.submitPin(pin);

**Comment by jeremiahAI** [comment]
Hi @chuksdsilent 
The reason this is occurring is that you're attempting to run the operations synchronously. Submitting the pin is meant to be after the `collectPin` callback has been called, so it should be implemented in the callback.

It seems you've been experiencing difficulty implementing the custom UI. You can check out our sample app to see how it was implemented, or send me a mail [here](mailto:varisiv@gmail.com) so we can set a meeting to walk through this.
