### ISSUE TITLE
Android library dependency issue

### ISSUE THREAD

**Issue by TalamusMedical** [Flutterwave/rave-android#25]
Hello, 

We are having issues with dependencies when using Flutterwave and Firebase in Android.

If we try to build the apk, there is an error:
Program type already present: com.google.gson.annotations.Expose

If we try to exclude some of the groups and modules from Flutterwave, there are various results.
If we exclude group ‘gson’, we can get to payment page, but after “Pay” button is tapped, we get an error:
An error ocurred while getting transaction fee.
If we exclude ‘gson-converter’, app crashes when it tries to open payment page.

Here are the dependencies we are using:
com.google.firebase:firebase-messaging:17.1.0
com.google.firebase:firebase-core:16.0.1'
com.github.Flutterwave:rave-android:1.0.23 (same thing happens with 1.0.18)

also, there is a
classpath ‘com.google.gms:google-services:4.0.1'
and plugin
apply plugin: 'com.google.gms.google-services'

We appreciate any support you can provide. 
Thank you.

**Comment by oluwatayo** [comment]
This happens when you are trying to build a release apk right??

**Comment by biodunalfet** [comment]
@TalamusMedical this error occurs when you use libraries that have the same sub-dependencies. It might help to print out your dependency tree [./gradlew app:dependencies] to see which libraries are using what dependencies, inspect for duplicates and exclude the duplicated dependencies.
