### ISSUE TITLE
Going live on the dashboard does not remove the "You are currently on staging mode" ribon and Live api keys are rejected

### ISSUE THREAD

**Issue by mwakaambrose** [Flutterwave/rave-android#253]
Hi, I need help!

I have switched to live on the dashboard but  the "You are currently on staging mode" ribbon and Live api keys are rejected.
I am using the rave ui and suplying the correct live keys.

I have even tried regenerating new keys but the issues still persists.

My rave ui version is 2.1.22
`implementation 'com.github.flutterwave.rave-android:rave_android:2.1.22'`

**Comment by deedatbilla** [comment]
Have u tried setting onStagingEnv(boolean) to false

**Comment by mwakaambrose** [comment]
I had not tried that, it wasn't documented. Setting it to false has worked, thanks @deedatbilla. Closing the issue.
