### ISSUE TITLE
Api issues

### ISSUE THREAD

**Issue by vishnukumar7** [Flutterwave/rave-android#259]
Hi Team,

1. login to flutter dashboard
2. change to test mode.
3. go to setting then click to API tab then get public key and encryption key 
4. save in my project then run 
5. call API for card payment 
6. response : "Merchant cannot accept international payments at this time. Please contact support"

Test Cards 
card number : 5531886652142950 
expiry : 09/32  cvv : 564
otp : 3310
pin: 12345

Thank you.

**Comment by jeremiahAI** [comment]
Hi @vishnukumar7 , please contact the team at hi@flutterwavego.com to be assisted with this issue.

**Comment by vishnukumar7** [comment]
when go to card payment page then show us pay with amounts without call any api
Example :  pay button in "pay (500.00)"
