### ISSUE TITLE
OTP Dialog not coming up after entering card details

### ISSUE THREAD

**Issue by tibizy** [Flutterwave/rave-android#26]
After entering the card details, i am suppose to see a dialog to enter OTP, i do receive the otp, but i cant see the dialog.

**Comment by temiadesina** [comment]
Hi @tibizy can you help with more details around the transaction, what card was being used and did you see a screen to enter your pin before the OTP section?

**Comment by temiadesina** [comment]
Hi, @tibizy seems you are using the old version of the SDK, please can you update to the new version, 

All you need to do is update the dependency:

dependencies {
     compile 'com.github.Flutterwave:rave-android:1.0.25'
}

You can check out the repo to see what was added to the new version.

**Comment by tibizy** [comment]
Thanks @temiadesina , i did upgrade and was able to test.

**Comment by temiadesina** [comment]
Glad you could sort this out @tibizy
