### ISSUE TITLE
Getting successful response everytime.

### ISSUE THREAD

**Issue by yash23raj** [Flutterwave/rave-android#27]
I am using below library for rave payment 
    compile 'com.github.Flutterwave:rave-android:1.0.27'
But when I do payment process whether with right or wrong details every time its onActivityResult throws successful response.
What is the exact problem I didn't find it can you please give me the proper solution to get rid out of such problem.

**Comment by ebuprof** [comment]
@biodunalfet , please what happens when you use staging and when you don't?

**Comment by biodunalfet** [comment]
HI @ebuprof When you're on staging, your transactions are always successful is if you use the test cards an accounts. Also, all your transactions can be viewed via the rave sandbox dashboard [https://ravesandbox.flutterwave.com].
