### ISSUE TITLE
Amount is required

### ISSUE THREAD

**Issue by saintjab** [Flutterwave/rave-android#3]
I am checking out the Account payment and even though I entered the amount when I was initialising RavePayManager, I get a toast "amount is required" and then nothing happens. Card payment works fine though.

**Comment by biodunalfet** [comment]
Which version of the sdk are your using?

**Comment by saintjab** [comment]
Aha, I think I was using an older version 1.0.2, I had updated it and its working fine. I wouldn't have noticed the update if you didn't ask. Thanks

**Comment by itsibee** [comment]
This issue is back with the latest update
