### ISSUE TITLE
I am currently integrating rave and got confused at a point. i need urgent assistance please.

### ISSUE THREAD

**Issue by ebuprof** [Flutterwave/rave-android#31]
To explain better better.
My application handles payment collection for multiple merchants and each has different customers that pay to them.
So during configuration, i want to use main-account to be 'mine' and use sub-account to be 'each merchant's own'.
My questions;
1. Does rave support many sub-accounts?
2. If so how can i do this because i tried and it refused me from adding more sub-accounts.
3. How flexible is it on rave when handling settlements and where to charge from {i mean whether your 
    1.4% will be charged from main-account or sub-account}.
4. For number 3 above, i want to be able to specify where 1.4% should be charged from. Whether from main-account which can be mine or sub-account which is merchant own on each and every transactions.
5. How possible can this be done from the SDK side just like the way it's done on paystack.

**Comment by biodunalfet** [comment]
@temiadesina kindly help with this. Thanks

**Comment by Kenmobility** [comment]
Also, there is some thing else i need to know regarding this aspect, if subaccounts can be created on rave, how can one specify the particular sub account that the transaction will be settled to and declare a particular flat amount or percentage to be settled to the main account which should override the split_value used during the creation of that sub-account on any transaction using the sdk.

**Comment by biodunalfet** [comment]
@ebuprof Split payments is available on Rave. You can learn more about this here https://developer.flutterwave.com/docs/split-payment
