### ISSUE TITLE
Storing your SECRET KEY on the user's device

### ISSUE THREAD

**Issue by farsheel** [Flutterwave/rave-android#40]
Hi,
the doc says we should pass  SECRET KEY using `setSecretKey(secretKey)` . is it safe to store secret key in client device? 
i think secret keys should be handled in server side.

or any workarounds to store secret key in client device safely?

**Comment by biodunalfet** [comment]
Hi @farsheel. I agree with you. It's stated in the documentation that your secret key should not be stored on the user's device. You can fetch it securely from your server.
