### ISSUE TITLE
M-Pesa Delayed in Android

### ISSUE THREAD

**Issue by justkeyo** [Flutterwave/rave-android#46]
Hi,
I have integrated rave for android into my android app.
In both sandbox and live, there is a latency affecting KE M-Pesa initiated payments where the STK Push to debit the customers M-Pesa is slower than Rave's listener checking for the posted transaction. This is causing misaligned transactions where the customers M-Pesa is debited and payment reflected successfully on the dashboard but the response to confirm the transaction is slow to the users device.

Logs are {"status":"error","message":"Not transaction found","data":{"code":"NO TX","message":"Not transaction found"}.

Can anyone help with this?

**Comment by biodunalfet** [comment]
Hi @justkeyo, I'm currently investigating this

**Comment by justkeyo** [comment]
> Hi @justkeyo, I'm currently investigating this

Hi,
Have you made any headway with the issue?

**Comment by biodunalfet** [comment]
Hi @justkeyo 
Yes. The above logs you pasted are just showing the status of the transaction as at when the time the log was created. Once the mpesa transaction is completed by the user, the transaction becomes successful and in `onActivityResult` you get the final status of the transaction.

**Comment by justkeyo** [comment]
Hi @biodunalfet @solejay @c0depanda @joeolaoye 

{"status":"error","message":"Not transaction found","data":{"code":"NO TX","message":"Not transaction found"}.

The above logs indicate the transaction is not aligned with the status of the transaction both on the dashboard and on the customer phone.

The customer M-Pesa account remains debited, there is evidence of the transaction on the dashboard but the activity result shows that no such transaction exists hence this is an error of misalignment which we need to address. 

Is there a way to increase this period of confirming the transaction?

**Comment by biodunalfet** [comment]
This issue has been fixed :)
