### ISSUE TITLE
Error Toast while when pay is clicked

### ISSUE THREAD

**Issue by Marcusjnr** [Flutterwave/rave-android#5]
i have put all the required parameters and everything seems to work fine until i click pay when i click pay it shows a toast message saying an "an error occurred while retrieving transaction fee". Please why am i having this issue. Am i missing something

**Comment by biodunalfet** [comment]
Hi can you paste you initialization code here?

**Comment by Marcusjnr** [comment]
This is the code below

` new RavePayManager(UnlockSound.this).setAmount(100.0)
                                    .setCountry("Nigeria")
                                    .setCurrency("NGN")
                                    .setEmail(getEmailInput)
                                    .setfName(tinyDb.getString("Username"))
                                    .setNarration("You are about the purchase the unlocksound premium feature")
                                    .setPublicKey("publickey")
                                    .setSecretKey("secretkey")
                                    .setTxRef(random())
                                    .acceptAccountPayments(true)
                        .acceptCardPayments(true)
                        .onStagingEnv(true)
                        .withTheme(R.style.DefaultThemeRave)
                                    .initialize();`

**Comment by biodunalfet** [comment]
Are you using version 1.0.4?

**Comment by Marcusjnr** [comment]
yes i am using version 1.0.4

**Comment by biodunalfet** [comment]
Okay. Check the logs. Filter for the tag "ravepay". G

**Comment by Marcusjnr** [comment]
Didn't find that but i did find something like this 
{"status":"error","message":"Invalid public key passed","data":{"code":"INV_PUBK","message":"Invalid public key passed"}}
but then the public key is correct from my dashboard
it gave me a link to 
http://flw-pms-dev.eu-west-1.elasticbeanstalk.com/flwv3-pug/getpaidx/api/fee
and the link says 
getpaidx not active or added

**Comment by biodunalfet** [comment]
Did you get the keys from rave.frontendpwc.com?

**Comment by Marcusjnr** [comment]
yes when i generated a checkout button

**Comment by biodunalfet** [comment]
You're using the live keys. You should set the value of `onStagingEnv()` to false instead of true.

**Comment by Marcusjnr** [comment]
oooh thank you very much i appreciate . That particular method was not explained, anyway it worked, but when it wants to charge and the user presses yes it brings out a toast saying "Compliance required please contact support". Why this please

**Comment by biodunalfet** [comment]
You have to complete your compliance form on the dashboard

**Comment by wealsegun** [comment]
Have tried everything still the same error please how did you resolve this???
