### ISSUE TITLE
Getting error in Release build in android - flutterwave

### ISSUE THREAD

**Issue by zohabAli** [Flutterwave/rave-android#52]
I am using flutterwave in android and it works perfectly in debug build but in Release build it crash even before asking for READ PHONE STATE permission
This is what I get as error

> Unable to find generated Parcelable class for com.flutterwave.raveandroid.l, verify that your class is configured properly and that the Parcelable class com.flutterwave.raveandroid.l$$Parcelable is generated by Parceler.

**Comment by biodunalfet** [comment]
Hi @zohabAli. Are you using Proguard?

**Comment by zohabAli** [comment]
Yes I am using proguard

**Comment by zohabAli** [comment]
@biodunalfet although I am ignoring its warning

**Comment by biodunalfet** [comment]
From your error it shows that the one of the sdk classes has been obfuscated `com.flutterwave.raveandroid.l`. Are you using the correct Proguard rules for the sdk? It's in the readme. Let me copy it here for you

```
keepclasseswithmembers public class com.flutterwave.raveandroid.** { *; }
dontwarn com.flutterwave.raveandroid.card.CardFragment
```

**Comment by zohabAli** [comment]
@biodunalfet Yes it worked! Thank you so much for your help. Respect!!!
