### ISSUE TITLE
outdated android-maven-gradle-plugin

### ISSUE THREAD

**Issue by oluwatayo** [Flutterwave/rave-android#56]
This library uses an old android-maven-gradle-plugin version 1.5 which introduces a bug with gradle > 4.0, therefore the dependencies used in this library such as Parcler, retrofit etc are not added to the library. This causes build to fail except the developer digs into this library and add those dependencies themselves.

**Comment by biodunalfet** [comment]
Hi @oluwatayo. Thanks for bringing our attention to this. We noticed this yesterday and are working on a fix as we speak.
