### ISSUE TITLE
payment unsuccessful in live mode

### ISSUE THREAD

**Issue by divakar1234** [Flutterwave/rave-android#60]
The transaction gets successful in the sandbox mode but when am trying to make a payment with live credentials (live mode) the status of transaction is showing "status-pending-validation" .The response I get is given below .Please refer to my problem and respond at the earliest as i have a project pending to be delivered to the client.

{"status":"Transaction successfully fetched","message":"Tx Fetched","data":{"id":22868068,"tx_ref":"1547535339096","order_ref":"URF_1547535937666_181235","flw_ref":"FLW110186027","transaction_type":"debit","settlement_token":null,"rave_ref":"RV315475359361283E4A711A97","transaction_processor":"FLW","status":"success-pending-validation","chargeback_status":null,"ip":"106.215.83.222:43156","device_fingerprint":"866132036753261","cycle":"one-time","narration":"CARD Transaction ","amount":1,"appfee":0.04,"merchantfee":0,"markupFee":null,"merchantbearsfee":1,"charged_amount":1,"transaction_currency":"NGN","system_type":null,"payment_entity":"card","payment_id":"1609578","fraud_status":"ok","charge_type":"normal","is_live":0,"createdAt":"2019-01-15T07:05:42.000Z","updatedAt":"2019-01-15T07:05:42.000Z","deletedAt":null,"merchant_id":31730,"addon_id":3,"customer.id":10681964,"customer.phone":null,"customer.fullName":"Divakar ","customer.customertoken":null,"customer.email":"aaa@gmail.com","customer.createdAt":"2019-01-15T07:05:36.000Z","customer.updatedAt":"2019-01-15T07:05:36.000Z","customer.deletedAt":null,"customer.AccountId":31730,"card":{"expirymonth":"09","expiryyear":"21","cardBIN":"472254","last4digits":"6470","brand":"VISA ICICI BANK LTD.CREDIT","card_tokens":[{"shortcode":"fb22d","embedtoken":"flw-t1nf-52e3dee57ba0583e2d0fb98cdcb6045d-k3n"}],"life_time_token":"flw-t1nf-52e3dee57ba0583e2d0fb98cdcb6045d-k3n"},"meta":[{"id":55743212,"metaname":"sdk","metavalue":"android","createdAt":"2019-01-15T07:05:37.000Z","updatedAt":"2019-01-15T07:05:37.000Z","deletedAt":null,"getpaidTransactionId":24852043}],"flwMeta":{"chargeResponse":"02","chargeResponseMessage":"Pending, Validation","VBVRESPONSEMESSAGE":"N\/A","VBVRESPONSECODE":"N\/A","ACCOUNTVALIDATIONRESPMESSAGE":null,"ACCOUNTVALIDATIONRESPONSECODE":null}}}

**Comment by Davingsdev** [comment]
> Hi, please confirm if you're still having this issue.

I seem to be having this same issue even with the updated version (com.github.Flutterwave.rave-android:rave_android:2.1.1)

**Comment by jeremiahAI** [comment]
@Davingsdev , please share details of the type of charge you're attempting.
Currency, payment method, verification method (i.e. PIN, OTP, no verification, etc., if it's a card transaction)

**Comment by Davingsdev** [comment]
It's a card transaction

This is how I implemented it  in this link :

https://github.com/Flutterwave/rave-android/issues/213#issuecomment-657752748

**Comment by jeremiahAI** [comment]
Resolved under another [thread](https://github.com/Flutterwave/rave-android/issues/213).
