### ISSUE TITLE
Issues with Live environment

### ISSUE THREAD

**Issue by wealsegun** [Flutterwave/rave-android#61]
Didn't find that but i did find something like this
{"status":"error","message":"Invalid public key passed","data":{"code":"INV_PUBK","message":"Invalid public key passed"}}
but then the public key is correct from my dashboard

**Comment by Whales1992** [comment]
> hi @wealsegun, you are getting invalid public key passed because you are either passing your rave sandbox public key to the live endpoint or passing your rave live public key to the test endpoint, please check this to ensure you are passing the right keys to the right endpoints.

so true! I had same issue integrating with paystack SDK but got ride of it using this kind of answer.
