### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by gagan50** [Flutterwave/rave-android#62]
java.lang.NullPointerException: println needs a message

code->

 new RavePayManager(this)
                .setAmount(10)
                .setCountry("NG")
                .setCurrency("NGN")
                .setEmail("abc@mailinator.com")
                .setfName("aa ")
                .setlName("a")
                 .setPublicKey("-------------------")
                .setEncryptionKey("--------------")
               .acceptAccountPayments(false)
                .acceptCardPayments(true)
                .acceptMpesaPayments(false)
                .acceptAchPayments(false)
                .acceptGHMobileMoneyPayments(false)
                .acceptUgMobileMoneyPayments(false)
                .onStagingEnv(true)
                .allowSaveCardFeature(false)
                .isPreAuth(false)
                .initialize();

**Comment by Whales1992** [comment]
This is really not an issue, simple check where you're using something like Log,
if the log is not getting a result to log,  then you will have this kind of crash, simple append an empty string to your expected log result.

**Comment by biodunalfet** [comment]
@gagan50 for us to help with this issue, you need to paste the full stacktrace.
