### ISSUE TITLE
Amount is Require

### ISSUE THREAD

**Issue by itsibee** [Flutterwave/rave-android#67]
I know this issue existed before and an update fixed it and I was using the service well before but right now after updating to 1.0.35, the issue is back and I cant complete my transactions.

**Comment by bolaware** [comment]
Hello @itsibee , can you provide more info like your `RavePayManager` initializer so we can reproduce the issue you are having on our end?

**Comment by itsibee** [comment]
Ok. So i updated to 1.0.35 becuase the prevous version i was using didnt include the encryption key. After updating that and include the encryption key I initialize the transaction on the app. After inserting my card details I get a confirmation of the amount I selected. And after accepting, it falls and gives an "Amount required" response. If its able to give me the confirmation message of the amount being paid then still fail, then It seem there's an issue. 

RavePayManager(activity).setAmount(amountInDouble)
                    .setCountry(nigeria)
                    .setCurrency(naira)
                    .setEmail(email)
                    .setfName(fName)
                    .setlName(lName)
                    .setPublicKey(publicKey)
                    .setEncryptionKey(encKey())
                     .onStagingEnv(false)
                    .setTxRef(ref)
                    .initialize();

**Comment by bolaware** [comment]
Still not able to reproduce your error with version `1.0.35`, I used this initializer, try it and see if it works for you too.Its a staging transaction
```
new RavePayManager(MainActivity.this)
                        .setAmount(Double.parseDouble("110"))
                        .setCountry("NG")
                        .setCurrency("NGN")
                        .setEmail("ebidhaa.ng@gmail.com")
                        .setfName("azeez")
                        .setlName("adio")
                        .setPublicKey("FLWPUBK-e634d14d9ded04eaf05d5b63a0a06d2f-X")
                        .setEncryptionKey("bb9714020722eb4cf7a169f2")
                        .setTxRef("jjjfjffj")
                        .onStagingEnv(true)
                        .initialize();
```
