### ISSUE TITLE
shouldDisplayFee(boolean) is not available

### ISSUE THREAD

**Issue by kelvinogwa** [Flutterwave/rave-android#76]
` new RavePayManager(Checkout.this).setAmount((int)Math.ceil(selectedCarPrefs.getLong("TOTAL", 0)))
                                                    .setCountry("KE")
                                                    .setCurrency("KES")
                                                    .setEmail(email)
                                                    .setfName(fname)
                                                    .setlName(lname)
                                                    .setNarration("Payment for booking " + bookingId)
                                                    .setPublicKey("test")
                                                    .setEncryptionKey("test")
                                                    .setTxRef(bookingId)
                                                    .acceptAccountPayments(true)
                                                    .acceptCardPayments(true)
                                                    .acceptMpesaPayments(false)
                                                    .acceptAchPayments(false)
                                                    .acceptGHMobileMoneyPayments(false)
                                                    .acceptUgMobileMoneyPayments(false)
                                                    .onStagingEnv(true)
                                                    .allowSaveCardFeature(true)
                                                    .setMeta(meta)
                                                    .withTheme(R.style.DefaultTheme)
                                                    .shouldDisplayFee(true)// could not resolve this method
                                                    .isPreAuth(true)
                                                    .initialize();`

**Comment by kelvinogwa** [comment]
The shouldDisplayFee(boolean) method is not available

**Comment by bolaware** [comment]
@kelvinogwa We are going to add the implementation for `shouldDisplayFee(boolean)` .For now you will have to do without it. Thanks for bringing our attention to it

**Comment by bolaware** [comment]
https://github.com/Flutterwave/rave-android/pull/77 requested a merge for this here

**Comment by biodunalfet** [comment]
@kelvinogwa this feature is now available in version `1.0.37`
