### ISSUE TITLE
Failed to Retrieve Card

### ISSUE THREAD

**Issue by kelvinogwa** [Flutterwave/rave-android#78]
Upon testing with local cards I am receiving the error "Failed to retrieve card"  This error is not documented in Rave Errors thus can not deduce the issue.

**Comment by biodunalfet** [comment]
@kelvinogwa Do you mean local Nigerian cards?

**Comment by kelvinogwa** [comment]
Kenyan Local as well  as the MasterCard test card

**Comment by jeremiahVaris** [comment]
@kelvinogwa, are you using test keys?

Please paste your RavePayManager initialization code here.

**Comment by kelvinogwa** [comment]
` new RavePayManager(Checkout.this).setAmount((int) Math.ceil(selectedCarPrefs.getLong("TOTAL", 0)))
                                                    .setCountry("KE")
                                                    .setCurrency("KES")
                                                    .setEmail(email)
                                                    .setfName(fname)
                                                    .setlName(lname)
                                                    .setNarration("Payment for booking " + bookingId)
                                                    .setPublicKey("FLWPUBK_TEST-470969c6c4f10210e539a108ace60d6e-X")
                                                    .setEncryptionKey("FLWSECK_TESTed960a6732b3")
                                                    .setTxRef(bookingId)
                                                    .acceptAccountPayments(true)
                                                    .acceptCardPayments(true)
                                                    .acceptMpesaPayments(false)
                                                    .acceptAchPayments(false)
                                                    .acceptGHMobileMoneyPayments(false)
                                                    .acceptUgMobileMoneyPayments(false)
                                                    .onStagingEnv(true)
                                                    .allowSaveCardFeature(true)
                                                    .setMeta(meta)
                                                    .withTheme(R.style.DefaultTheme)
                                                    .isPreAuth(true)
                                                    .shouldDisplayFee(true)
                                                    .showStagingLabel(true)
                                                    .initialize();`

I have removed the keys and replaced them with "test"

**Comment by jeremiahVaris** [comment]
Set .isPreAuth() to false for your tests.

**Comment by jeremiahVaris** [comment]
Or are you trying to simulate a preAuth transaction?

**Comment by kelvinogwa** [comment]
I set preAuth to false and it proceeds. Thank you. I did not understand the difference between the two but now I do
