### ISSUE TITLE
Configuring Proguard is missleading 

### ISSUE THREAD

**Issue by itsibee** [Flutterwave/rave-android#83]
According to the documentation only two rules need to be added for the library to work but In reality I had to add about 12 before I got it to work in my previous app. Now I'm making a new app with updated dependencies and those rules did not solve the problem. Please update the documentation to show all rules that need to be added for Flutterwave library to work when proguard is enabled. I am certain that my issues is from the library as the last time I had to look through the library to find any import used that could have an issue with minified codes and add an exception to that in my proguard rules.  It does not make sense to do this every time I have a proguard related issue. Please update the documentation, Thanks.

**Comment by biodunalfet** [comment]
The documentation page has now been linked to the GitHub readme which is up to date.
