### ISSUE TITLE
An error occurred while retrieving transaction fee

### ISSUE THREAD

**Issue by devendroid** [Flutterwave/rave-android#87]
I'm getting this toast message (An error occurred while retrieving transaction fee) on pay and logcat showing this:
{"status":"error","message":"Only test cards allowed","data":{"code":"CARD_ERR","message":"Only test cards allowed"}}
I using SDK ver 1.0.38,
Setting onStagingEnv(true),
Using test keys and test cards.

What i missing..?

**Comment by biodunalfet** [comment]
@devendroid please can you paste your initialisation code here?

**Comment by jeremiahVaris** [comment]
@devendroid 
The [test cards page](https://developer.flutterwave.com/docs/test-cards) has been updated with the working test cards now. You can try again with one of them.

**Comment by devendroid** [comment]
still getting same error tried with 2 different cards..!

**Comment by devendroid** [comment]
Hi @biodunalfet, initialization code is:
```
new RavePayManager(getActivity()).setAmount(12)
                                .setCountry("RW")
                                .setCurrency("RWF")
                                .setEmail("d@d.com")
                                .setfName("dev")
                                .setlName("endra")
                                .setNarration("")
                                .setPublicKey("xxxxxxxxxx")
                                .setEncryptionKey("xxxxxxxxx")
                                .setTxRef("12345")
                                .acceptAccountPayments(true)
                                .acceptCardPayments(true)
                                .acceptMpesaPayments(true)
                                .acceptAchPayments(true)
                                .acceptGHMobileMoneyPayments(true)
		                .acceptUgMobileMoneyPayments(true)
                                .onStagingEnv(true)
                                .shouldDisplayFee(true)
                                .showStagingLabel(true)
                                .initialize(); 
```

**Comment by jeremiahVaris** [comment]
@devendroid, please what test card did you use?
I just used 
`4242 4242 4242 4242
cvv: 812
Expiry: 01/21
Pin 3310
otp 12345`

And it worked fine. Please test and revert.

**Comment by devendroid** [comment]
@jeremiahVaris , Checked with this also, but no luck.

**Comment by jeremiahVaris** [comment]
That means it's an issue regarding your API keys. Please send a mail to developers@flutterwavego.com to have this resolved.

**Comment by devendroid** [comment]
OK @jeremiahVaris ,  Thanks for your help and suggestion.
