### ISSUE TITLE
Code updated on github

### ISSUE THREAD

**Issue by gagan50** [Flutterwave/rave-android#9]
Are you sure this code is working perfectly??
Because while implememnts this code i got null pointer exception

**Comment by biodunalfet** [comment]
Hi, 
At what point do you get the NullPointerException? Can I see your initialization code?

**Comment by gagan50** [comment]
Error:(2, 0) Plugin with id 'com.github.dcendents.android-maven' not found.
<a href="openFile:/home/pro37/AndroidStudioProjects/UseMyRide/raveandroid/build.gradle">Open File</a>

**Comment by gagan50** [comment]
firstly when i add android module in my project i get this error

**Comment by biodunalfet** [comment]
You are not adding the library correctly. Did you add jitpack to your root build.gradle file?

**Comment by gagan50** [comment]
Okay i will add it.
May i know is it supported for Greenland??

**Comment by gagan50** [comment]
yes i have added that

**Comment by biodunalfet** [comment]
RavePay is not supported in Greenland. Hope your issue has been solved

**Comment by gagan50** [comment]
in which country is supported

**Comment by gagan50** [comment]
may i know how can i get public key ,secret key and url that are used inside how can i get that all?
they all are same for everytime or it may be changed ?

**Comment by iolufemi** [comment]
Hi @gagan50 

We support Africa, US and UK. Can you please drop us a mail at hi@flutterwavego.com, so we can know more about your use case. 

You can get your public key and secret by signing up at https://ravepay.co. On signing up, you need to create a Rave checkout button. Once that is done, you will be able to access your public key and secret. Kindly visit our documentation at https://flutterwavedevelopers.readme.io/ on how to integrate and get the necessary API endpoints. 

For integration and testing, you should use our sandbox environment at rave.frontendpwc.com

**Comment by gagan50** [comment]
Hello sir

Hope you are doing great !!

Please let me know that how  can i get  Client Key

Gagandeep Singh
