### ISSUE TITLE
Stuck on push notification dialog

### ISSUE THREAD

**Issue by bensek** [Flutterwave/rave-android#99]
I just implemented flutterwave in my mobile app, but the Ug mobile money payments gets stuck on the "A push notification has been sent to your phone....". The push notification dont popup. I dont know what am missing.

**Comment by biodunalfet** [comment]
@bensek has this been resolved?

**Comment by bensek** [comment]
Yes it was resolved by adding an amount greater than 500UGX and using the api with LIVE keys not sandbox.

**Comment by Isaacn123** [comment]
yah thanks was stack at the same screen was testing with value bellow 500UGX.
